[book]
authors = ["sineemore", "hXtreme"]
language = "en"
multilingual = false
src = "src"
title = "suckless-101"

[output.html]
default-theme = "ayu"
mathjax-support = true

[output.html.fold]
enable = true

[output.html.search]
enable = true
